export const GOOGLE_API_KEY="AIzaSyBzlDrVDrVz-5QamhXbIgRU3G-tUqdyvhQ";
export const GOOGLE_API_KEY_PLACE="AIzaSyA1pGhJISpECebEQRto9GKck-CWiSBw088";
export const GOOGLE_API_KEY_GEOLOCATION="AIzaSyBqKUBIswNi5uO3xOh4Boo8kSJyJ3DLkhk";
export const GOOGLE_API_KEY_TIME="AIzaSyAJ6p8VJoTHAbEh9W6880RTjky0JiJZ0L4";
//AIzaSyBzlDrVDrVz-5QamhXbIgRU3G-tUqdyvhQ